### ISSUE TITLE
aTech URI

### ISSUE THREAD

**Issue by dwilson2547** [adamcooke/bound#5]
What should be entered for the URI redirect?

**Comment by adamcooke** [comment]
I don't understand the question.

**Comment by dwilson2547** [comment]
Sorry, that was quite vague. When I try to set up aTech authentication, it asks for a redirect URI for the application for API authentication and I can't seem to get that part working, I always get "error=redirect_uri_mismatch&error_description=parameter+redirect_uri+does+not+match+registered+uri" after I click the login for the first time link

**Comment by adamcooke** [comment]
Oh. It should be something like `https://yourdomain.com/auth/atech/callback`
