### ISSUE TITLE
Missing licence? :)

### ISSUE THREAD

**Issue by mario** [adamcooke/bound#6]

**Comment by herono** [comment]
Sehr geehrte Damen und Herren,

bis einschließlich 12. Mai 2017 bin ich nicht erreichbar. Eingegangene Nachrichten werde ich ab dem 15. Mai bearbeiten. Ihre Nachricht wird NICHT weitergeleitet. Bitte wenden Sie sich in dieser Zeit gegebenenfalls an meine Kollegen:

Herr Hoyer (hoyer@online-now.de)
Herr Böneke (boeneke@online-now.de)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++

Dear Sirs and Madams,

up to and including the 12th of May 2017 I am not available. Received e-mails I will process from the 15th of May. Your message will NOT be forwarded. If needed, please contact my colleagues at this time:

Mr. Hoyer (hoyer@online-now.de)
Mr. Böneke (boeneke@online-now.de)


Mit freundlichen Grüßen,
best regards,

Johannes Herzfeldt

--------------------------------------------------
Online Now! GmbH
Agentur für digitale Kommunikation
Kastanienallee 26
14052 Berlin

Tel +49 30 615082-120
Fax +49 30 615082-222
E-Mail: herzfeldt@online-now.de
Web: http://www.online-now.de/

Geschäftsführer: Dr. Maximilian Hoyer
Handelsregister: Amtsgericht Berlin-Charlottenburg HRB 57835
Ust.-ID: DE 176635553

**Comment by adamcooke** [comment]
Added
